version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

jobs:
  build-android:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.9f1
      resource_class: xlarge
      target_platform: android
    steps:
      - checkout
      - unity/build:
          build-target: Android

  build-ios:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.9f1
      resource_class: xlarge
      target_platform: ios
    steps:
      - checkout
      - unity/build:
          build-target: iOS

workflows:
  build-unity-project:
    jobs:
      - build-android:
          context: unity
      - build-ios:
          context: unity
