version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

jobs:
  build-android:
    executor:
      editor_version: 2021.3.9f1
      name: unity/ubuntu
      resource_class: xlarge
      target_platform: android
    steps:
      - checkout
      - unity/build:
          build-target: Android

workflows:
  build-unity-project:
    jobs:
      - build-android:
          context: unity
      # - unity/build:
      #     name: build-ios
      #     build-target: iOS
          
      #     executor:
      #       editor_version: 2021.3.9f1
      #       name: unity/ubuntu
      #       resource_class: xlarge
      #       target_platform: ios
