version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

workflows:
  build-unity-project:
    jobs:
      - unity/build:
          name: build-android
          build-target: Android
          context: unity
          executor:
            editor_version: 2021.3.9f1
            name: unity/ubuntu
            resource_class: xlarge
            target_platform: android
      - unity/build:
          name: build-ios
          build-target: iOS
          context: unity
          executor:
            editor_version: 2021.3.9f1
            name: unity/ubuntu
            resource_class: xlarge
            target_platform: ios
