version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  unity: game-ci/unity@1.1.0

jobs:
  build-android:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.9f1
      resource_class: xlarge
      target_platform: android
    steps:
      - checkout
      - unity/prepare-env
      - unity/build:
          build-target: Android
          compress: false
          store-artifacts: false
      - ruby/install-deps

  # build-ios:
  #   executor:
  #     name: unity/ubuntu
  #     editor_version: 2021.3.9f1
  #     resource_class: xlarge
  #     target_platform: ios
  #   steps:
  #     - checkout
  #     - unity/prepare-env
  #     - unity/build:
  #         build-target: iOS
  #         compress: false
  #         store-artifacts: false
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - Builds/iOS/iOS

  build-ios:
    executor:
      name: unity/macos
      editor_version: 2021.3.9f1
      resource_class: large
    steps:
      - checkout
      - unity/prepare-env
      - unity/build:
          build-target: iOS
          compress: false
          store-artifacts: false
      - ruby/install-deps

workflows:
  build-unity-project:
    jobs:
      - build-android:
          context: unity
      - build-ios:
          context: unity
