version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

workflows:
  build-unity-project:
    jobs:
      - unity/build:
          build-target: Android
          context: unity
          executor:
            editor_version: 2021.3.9f1
            name: unity/ubuntu
            resource_class: large
            target_platform: android
